import = [
    "~/.config/alacritty/themes/themes/material_theme.toml"
]

[shell]
program = "/usr/bin/fish"

[window]
dynamic_padding = true
opacity = 0.99
padding = {x = 2, y = 0}
decorations = "None"
blur = true

[env]
term = "xterm-265color"

[font]
normal = {family = "JetBrainsMono NerdFontMono", style = "SemiBold"}
italic = {family = "JetBrainsMono NerdFontMono", style = "Italic"}
bold = {family = "JetBrainsMono NerdFontMono", style = "Bold"}
size = 13
